/**
 * Sidebars are fully autogenerated from the `docs/` directory structure.
 *
 * Ordering is controlled by:
 *   - `_category_.json` files (category label + position + generated index page)
 *   - `sidebar_position` in each document's front matter
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
